apiVersion: v1
kind: Service
metadata:
  name: carvision-api
  namespace: carvision
spec:
  selector:
    app: carvision-api
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  type: ClusterIP
