apiVersion: v1
kind: ConfigMap
metadata:
  name: carvision-config
  namespace: carvision
data:
  API_CORS_ORIGINS: "*"
  JWT_EXPIRE_MINUTES: "480"
  FRONTEND_PUBLIC_SCHEME: "https"
  FRONTEND_PUBLIC_PORT: "443"
  LOG_LEVEL: "INFO"
