apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: carvision
  namespace: carvision
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
spec:
  ingressClassName: nginx
  rules:
    - host: carvision.example.com
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: carvision-api
                port:
                  number: 8000
          - path: /stream
            pathType: Prefix
            backend:
              service:
                name: carvision-api
                port:
                  number: 8000
          - path: /media
            pathType: Prefix
            backend:
              service:
                name: carvision-api
                port:
                  number: 8000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: carvision-frontend
                port:
                  number: 80
